stages:
  - stage_build
  - stage_test
  - stage_deploy

image: mcr.microsoft.com/dotnet/sdk:8.0
variables: 
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

test_job:
  stage: stage_test
  services:
    - docker:20.10.12-dind
  script: 
    - apt-get update && apt-get install -y docker-compose
    - echo "tests started"
    - echo "start docker container"
    - docker compose up db -d
    - dotnet test
  after_script: 
    - echo "tests finished"
    - docker compose down